//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class fk_auftrag
    {
        public int SheetNr { get; set; }
        public string AuftragsNr { get; set; }
        public Nullable<int> AuftragsKennung { get; set; }
        public Nullable<int> BelegKreis { get; set; }
        public string KundenNr { get; set; }
        public string LieferantenNr { get; set; }
        public string ProjektNr { get; set; }
        public string KundenMatchcode { get; set; }
        public Nullable<int> VorgangNr { get; set; }
        public Nullable<int> SammelRgNr { get; set; }
        public string BestellNr { get; set; }
        public string Bearbeiter { get; set; }
        public Nullable<int> Kontierung_DebitorenNr { get; set; }
        public Nullable<int> Kontierung_Forderungskonto { get; set; }
        public Nullable<int> bKontierung_Ausland { get; set; }
        public string Kontierung_EG_ID_Nr { get; set; }
        public string Konditionen_Zahlungsbedingung { get; set; }
        public string Konditionen_Skonto_Text { get; set; }
        public string Konditionen_Skonto_Text_Rechng { get; set; }
        public Nullable<int> Konditionen_Ziel_Tage { get; set; }
        public Nullable<int> Konditionen_Skonto_Tage { get; set; }
        public Nullable<float> Konditionen_Skonto_Proz { get; set; }
        public Nullable<int> Konditionen_PreisgrpNr { get; set; }
        public Nullable<float> Konditionen_Rabatt { get; set; }
        public Nullable<float> Konditionen_Rabatt_Proz { get; set; }
        public Nullable<int> Konditionen_Waehrung { get; set; }
        public Nullable<int> Konditionen_Zahlungsart { get; set; }
        public string Konditionen_Lieferart { get; set; }
        public Nullable<int> bKonditionen_ist_brutto { get; set; }
        public Nullable<int> bKonditionen_keine_ust { get; set; }
        public Nullable<int> bKonditionen_rabatt_direkt { get; set; }
        public Nullable<int> bKonditionen_Monatsrechnung { get; set; }
        public Nullable<int> bKonditionen_Lieferstop { get; set; }
        public Nullable<int> Kostenstelle { get; set; }
        public Nullable<int> Kostentraeger { get; set; }
        public string Anschrift_Anrede { get; set; }
        public string Anschrift_Firma { get; set; }
        public string Anschrift_Name { get; set; }
        public string Anschrift_Vorname { get; set; }
        public string Anschrift_Zusatz { get; set; }
        public string Anschrift_Ansprech { get; set; }
        public string Anschrift_Strasse { get; set; }
        public string Anschrift_HausNr { get; set; }
        public string Anschrift_Ort { get; set; }
        public string Anschrift_Plz { get; set; }
        public string Anschrift_Land { get; set; }
        public string Anschrift_Tel1 { get; set; }
        public string Anschrift_Tel2 { get; set; }
        public string Anschrift_Fax { get; set; }
        public string Anschrift_Email { get; set; }
        public string Texte_Kopftext { get; set; }
        public string Texte_Fusstext { get; set; }
        public Nullable<System.DateTime> Datum_erfassung { get; set; }
        public Nullable<System.DateTime> Datum_zahlung { get; set; }
        public Nullable<float> Summen_netto_haupt { get; set; }
        public Nullable<float> Summen_brutto_haupt { get; set; }
        public Nullable<float> Summen_netto_neben { get; set; }
        public Nullable<float> Summen_brutto_neben { get; set; }
        public Nullable<float> Summen_ust_gesamt { get; set; }
        public Nullable<float> Summen_abschlag_netto { get; set; }
        public Nullable<float> Summen_abschlag_brutto { get; set; }
        public Nullable<int> Summen_abschlag_ust_schluessel { get; set; }
        public Nullable<float> Summen_abschlag_ust { get; set; }
        public Nullable<float> Summen_abschlag_forderung { get; set; }
        public Nullable<float> Summen_abschlag_erhalten { get; set; }
        public Nullable<float> Summen_gesamt { get; set; }
        public Nullable<int> bStatus_lagergebucht { get; set; }
        public Nullable<int> bStatus_gebucht { get; set; }
        public Nullable<int> bStatus_uebernommen { get; set; }
        public Nullable<int> bStatus_gedruckt { get; set; }
        public Nullable<int> bStatus_exportiert { get; set; }
        public Nullable<int> bStatus_geliefert { get; set; }
        public Nullable<int> bStatus_gemahnt { get; set; }
        public Nullable<int> bStatus_bezahlt { get; set; }
        public Nullable<int> bStatus_liefer_fakturiert { get; set; }
        public Nullable<int> bStatus_export_ascii { get; set; }
        public Nullable<int> bStatus_export_datev { get; set; }
        public Nullable<int> bStatus_abschlag { get; set; }
        public Nullable<int> bStatus_weitergefuehrt { get; set; }
        public Nullable<int> bStatus_erfassung_komplett { get; set; }
        public Nullable<int> bStatus_internet { get; set; }
        public Nullable<int> Verweis_weiter_aus_nr { get; set; }
        public Nullable<int> Verweis_weiter_in_nr { get; set; }
        public Nullable<int> Verweis_SchlussRgNr { get; set; }
        public Nullable<int> Verweis_GesamtRgNr { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<int> Status_drucken { get; set; }
        public Nullable<int> Status_gedruckt { get; set; }
        public Nullable<System.DateTime> System_created { get; set; }
        public string System_created_user { get; set; }
        public Nullable<System.DateTime> System_updated { get; set; }
        public string System_updated_user { get; set; }
        public Nullable<int> bStatus_gemailt { get; set; }
        public Nullable<int> bStatus_frankiert { get; set; }
        public Nullable<float> Summen_roherloes { get; set; }
        public Nullable<float> Summen_roherloesEK { get; set; }
        public Nullable<float> Summen_roherloesVK { get; set; }
        public Nullable<int> bStatus_storniert { get; set; }
        public Nullable<int> bStornoOrgGebucht { get; set; }
        public Nullable<int> lStornoOrgKennung { get; set; }
        public Nullable<int> lAboID { get; set; }
        public Nullable<int> lAboVorlageID { get; set; }
        public Nullable<System.DateTime> tsAboBegin { get; set; }
        public Nullable<System.DateTime> tsAboEnde { get; set; }
        public Nullable<int> fAboAbgeschlossen { get; set; }
        public Nullable<int> lWiedervorlageID { get; set; }
        public Nullable<int> Konditionen_Skonto_Tage2 { get; set; }
        public Nullable<float> Konditionen_Skonto_Proz2 { get; set; }
        public string szRMA { get; set; }
        public string szLieferantSteuerNr { get; set; }
        public Nullable<int> bKontierungUmkehr_13b { get; set; }
        public Nullable<int> lKontierungFrage_13b { get; set; }
        public Nullable<int> lFkNumID { get; set; }
        public Nullable<System.DateTime> tsLieferTermin { get; set; }
        public string szUserdefined1 { get; set; }
        public string szUserdefined2 { get; set; }
        public string szUserdefined3 { get; set; }
        public Nullable<int> lAnschriftID { get; set; }
        public Nullable<float> dftSummen_Selbstkosten { get; set; }
        public Nullable<int> bSelbstkostenKomplett { get; set; }
        public Nullable<float> dftSummen_Gegeben { get; set; }
        public Nullable<int> bBarbeleg { get; set; }
        public Nullable<int> lKasseID { get; set; }
        public Nullable<int> lBonNr { get; set; }
        public Nullable<int> lZahlungsart { get; set; }
        public Nullable<System.DateTime> tsZahlung { get; set; }
        public Nullable<int> lKundengruppenID { get; set; }
        public Nullable<int> lVertreterID { get; set; }
        public Nullable<int> lBranchenID { get; set; }
        public string szAgetoID { get; set; }
        public Nullable<int> lHerkunft { get; set; }
        public Nullable<int> bStatus_Teilgezahlt { get; set; }
        public Nullable<int> lSammelRgnOrderUp { get; set; }
        public Nullable<int> lAbschlagRgnOrderUp { get; set; }
        public Nullable<System.DateTime> tsServiceZeitpunkt { get; set; }
        public string szKundendienstler { get; set; }
        public Nullable<int> bKV_verbindlich { get; set; }
        public Nullable<int> lAnschriftID_Service { get; set; }
        public Nullable<int> f2007Ready { get; set; }
        public Nullable<int> lElectronicInvoiceStatus { get; set; }
        public string szElectronicInvoiceFile { get; set; }
        public string szElectronicInvoiceGuid { get; set; }
        public Nullable<float> dftSumme_GewinnNetto_NAR { get; set; }
        public Nullable<int> bBarKasse { get; set; }
        public string szACCVersionInfo { get; set; }
        public Nullable<int> lProvEmpfaengerID { get; set; }
        public Nullable<int> lProvEmpfaengerVersionID { get; set; }
        public Nullable<float> dftSummen_Gewicht { get; set; }
        public string szLeistungsDatum { get; set; }
        public string szUserdefined4 { get; set; }
        public string szUserdefined5 { get; set; }
        public string szUserdefined6 { get; set; }
        public Nullable<int> bFixFaellig { get; set; }
        public Nullable<int> lTagVonMonat { get; set; }
        public Nullable<int> lTageVorlauf { get; set; }
        public Nullable<int> lStatusPoststelle { get; set; }
        public Nullable<int> lStatusNotiz { get; set; }
    }
}
